// Generated by CoffeeScript 1.6.3
(function() {
  var Email, app, express, http, mongoose, path, _ref;

  express = require('express');

  http = require('http');

  path = require('path');

  mongoose = require('mongoose');

  app = express();

  app.set('port', (_ref = process.env.PORT) != null ? _ref : 3000);

  app.set('views', __dirname + '/../views');

  app.set('view engine', 'jade');

  app.use(express.favicon());

  app.use(express.logger('dev'));

  app.use(express.bodyParser());

  app.use(express.methodOverride());

  app.use(app.router);

  app.use(express["static"](path.join(__dirname, '/../public')));

  mongoose.connect('mongodb://localhost/personalsite');

  Email = mongoose.model('Email', {
    name: String,
    email: String,
    subject: String,
    message: String
  });

  if ('development' === app.get('env')) {
    app.use(express.errorHandler());
  }

  app.get('/', function(req, res) {
    return res.render('index');
  });

  app.post('/sendemail', function(req, res) {
    var email, submitInfo;
    submitInfo = req.body;
    console.log(submitInfo);
    if (submitInfo.name && submitInfo.email && submitInfo.subject && submitInfo.message) {
      email = new Email(submitInfo);
      email.save();
      console.log("email", email);
      return res.send({
        success: "success"
      });
    } else {
      return res.send({
        failure: 'failure'
      });
    }
  });

  http.createServer(app).listen(app.get('port'), function() {
    return console.log('Express server listening on port ' + app.get('port'));
  });

}).call(this);
